---
title:  Data Preprocessing
author: Dimitri Leandro
date:   March, 2023
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
    toc_depth: 3
    number_sections: true
    code_folding: show
---

# Getting started

## Imports

```{r message=FALSE, warning=FALSE}
library(jsonlite)
library(stringr)
library(purrr)
library(dplyr)
library(lubridate)

Sys.setlocale('LC_TIME', 'C')
```

## Functions definitions

```{r}
getActivityDataFrame <- function(
    df,
    activity,
    remove_na     = TRUE,
    columnsPrefix = 'timelineObjects.activitySegment.'
){
  # getting rows where activity
  df_activity <- df[
    df$timelineObjects.activitySegment.activityType==activity & 
      !is.na(df$timelineObjects.activitySegment.activityType),
  ]
  
  # removing columns where all rows are null or na
  if(remove_na){
    df_activity <- df_activity[
      colSums(is.na(df_activity) | df_activity=='NULL') != nrow(df_activity)
    ]
  }
  
  # renaming columns by removing prefix
  colnames(df_activity) <- map(
    colnames(df_activity),
    function(col) str_replace(col, columnsPrefix, '')
  )
  
  return(df_activity)
}
```

```{r}
processActivityColumns <- function(
    df_activity, 
    column_mappings
){
  # keeping less accurate distance for coalesce purposes
  simple_distance <- df_activity$distance
  
  # renaming and selecting columns based on collection  
  df_activity <- df_activity %>%
    rename(column_mappings) %>%
    select(all_of(names(column_mappings)))
  
  # trying to keep accurate distance (better less accurate than null)
  df_activity$kilometers <- coalesce(df_activity$kilometers, simple_distance)

  # converting start timestamp to berlin timezone
  df_activity$startTimestamp <- as.POSIXct(
    x      = df_activity$startTimestamp,
    format = '%FT%T',
    tz     = 'Europe/Berlin'
  ) + hours(2)
  
  # converting end timestamp to berlin timezone
  df_activity$endTimestamp <- as.POSIXct(
    x      = df_activity$endTimestamp,
    format = '%FT%T',
    tz     = 'Europe/Berlin'
  ) + hours(2)
  
  # converting meters to kilometers
  df_activity$kilometers <- df_activity$kilometers/1000
  
  # duration of activity in hours
  df_activity$hours <- as.numeric(
    difftime(
      df_activity$endTimestamp,
      df_activity$startTimestamp,
      units = 'hours'
    )
  )
  
  # speed in km/h
  df_activity$speed <- df_activity$kilometers / df_activity$hours
  
  # categorical start timestamp: time of the day
  df_activity$timeOfDay <- cut(
    x              = hour(df_activity$startTimestamp), 
    breaks         = hour(hm('00:00', '06:00', '12:00', '18:00', '23:59')), 
    labels         = c('Night', 'Morning', 'Afternoon', 'Evening'), 
    include.lowest = TRUE
  )
  
  # day of week
  df_activity$weekday <- weekdays(df_activity$startTimestamp)
  
  # week of year
  df_activity$weekOfYear <- week(df_activity$startTimestamp)
  
  # month
  df_activity$month <- months(df_activity$startTimestamp)
  
  return(df_activity)
}
```

```{r}
getMonthActivityData <- function(dataset_path){
  # reading month raw data
  df <- as.data.frame(
    fromJSON(
      txt = dataset_path,
      flatten = TRUE
    )
  )
  
  # gathering preprocessed activity information
  month_activity_df <- rbind(
    processActivityColumns(
      getActivityDataFrame(df, 'CYCLING', FALSE), 
      cycling_column_mappings
    ),
    processActivityColumns(
      getActivityDataFrame(df, 'WALKING', FALSE), 
      walking_column_mappings
    ),
    processActivityColumns(
      getActivityDataFrame(df, 'IN_TRAIN', FALSE), 
      train_column_mappings
    ),
    processActivityColumns(
      getActivityDataFrame(df, 'IN_BUS', FALSE), 
      bus_column_mappings
    )
  )
  
  return(month_activity_df)
}
```

# Understanding the data structure

## Activity Segment

```{r}
# reading simple subsample json
df <- as.data.frame(
  fromJSON(
    txt = '../dataset/raw/simple_subsample.json',
    flatten = TRUE
  )
)
```

### Cycling

```{r}
# getting only cycling samples and its columns
df_cycling <- getActivityDataFrame(df, 'CYCLING')

# how the raw data looks like
head(df_cycling)
```

```{r warning=FALSE}
# mapping new names to the columns I'd like to keep
cycling_column_mappings <- c(
  'activityType'   = 'activityType',
  'startTimestamp' = 'duration.startTimestamp',
  'endTimestamp'   = 'duration.endTimestamp',
  'kilometers'     = 'waypointPath.distanceMeters'
)

# formatting columns
df_cycling <- processActivityColumns(df_cycling, cycling_column_mappings)

# how it looks like now
head(df_cycling)
```

### Walking

```{r}
# getting only walking samples and its columns
df_walking <- getActivityDataFrame(df, 'WALKING')

# how the raw data looks like
head(df_walking)
```

```{r}
# mapping new names to the columns I'd like to keep
walking_column_mappings <- cycling_column_mappings

# formatting columns
df_walking <- processActivityColumns(df_walking, walking_column_mappings)

# how it looks like now
head(df_walking)
```

### In Train

```{r}
# getting only train samples and its columns
df_train <- getActivityDataFrame(df, 'IN_TRAIN')

# how the raw data looks like
head(df_train)
```

```{r}
# mapping new names to the columns I'd like to keep
train_column_mappings <- c(
  'activityType'   = 'activityType',
  'startTimestamp' = 'duration.startTimestamp',
  'endTimestamp'   = 'duration.endTimestamp',
  'kilometers'     = 'transitPath.distanceMeters'
)

# formatting columns
df_train <- processActivityColumns(df_train, train_column_mappings)

# how it looks like now
head(df_train)
```

### In Bus

```{r}
# getting only bus samples and its columns
df_bus <- getActivityDataFrame(df, 'IN_BUS')

# how the raw data looks like
head(df_bus)
```

```{r}
# mapping new names to the columns I'd like to keep
bus_column_mappings <- train_column_mappings

# formatting columns
df_bus <- processActivityColumns(df_bus, bus_column_mappings)

# how it looks like now
head(df_bus)
```

### Writing CSVs

```{r}
# writing the simple subsample result
write.csv(
  x         = rbind(df_cycling, df_walking, df_train, df_bus), 
  file      = '../dataset/activities/simple_subsample_activities.csv', 
  row.names = FALSE
)
```

```{r}
# removing the previous variables for memory usage purposes
rm(df, df_cycling, df_walking, df_train, df_bus)
```

```{r}
# processing the actual data
write.csv(
  file      = '../dataset/activities/activities.csv', 
  row.names = FALSE,
  x         = rbind(
    getMonthActivityData('../dataset/raw/2022_APRIL.json'),
    getMonthActivityData('../dataset/raw/2022_MAY.json'),
    getMonthActivityData('../dataset/raw/2022_JUNE.json'),
    getMonthActivityData('../dataset/raw/2022_JULY.json'),
    getMonthActivityData('../dataset/raw/2022_AUGUST.json')
  )
)
```

## Place Visit

## Gathering latitude and longitude information
